#include "modules/recon/engine/reconwebinsights.h"

#include <QByteArrayView>
#include <QRegularExpression>

namespace {

QString extractVersion(const QByteArray &payload)
{
    static const QRegularExpression regex(QStringLiteral("((?:\\d+\\.){1,3}\\d+[a-z0-9\\-]*)"),
                                          QRegularExpression::CaseInsensitiveOption);
    const auto match = regex.match(QString::fromUtf8(payload));
    return match.hasMatch() ? match.captured(1) : QString();
}

bool hasHeader(const QList<QPair<QByteArray, QByteArray>> &headers, QByteArrayView header)
{
    const QByteArray target = header.toByteArray().toLower();
    for (const auto &pair : headers) {
        if (pair.first.toLower() == target) {
            return true;
        }
    }
    return false;
}

QString headerValue(const QList<QPair<QByteArray, QByteArray>> &headers, QByteArrayView header)
{
    const QByteArray target = header.toByteArray().toLower();
    for (const auto &pair : headers) {
        if (pair.first.toLower() == target) {
            return QString::fromUtf8(pair.second).trimmed();
        }
    }
    return QString();
}

void addFinding(QList<ReconFindingCandidate> &findings,
                QString severity,
                QString title,
                QString description,
                QString category,
                int penalty)
{
    findings.push_back({std::move(severity), std::move(title), std::move(description), std::move(category), penalty});
}

} // namespace

ReconWebAnalysis reconAnalyzeWebResponse(const ReconWebResponseInput &input)
{
    ReconWebAnalysis analysis;

    const QString serverHeader = headerValue(input.rawHeaders, "Server");
    const QString poweredByHeader = headerValue(input.rawHeaders, "X-Powered-By");
    const QString bodyText = QString::fromUtf8(input.bodyPreview);
    QString wafName;

    if (!hasHeader(input.rawHeaders, "content-security-policy")) {
        addFinding(analysis.findings, "medium", "CSP eksik", "Content-Security-Policy basligi eksik", "web", 15);
    }
    if (!hasHeader(input.rawHeaders, "strict-transport-security") && input.url.scheme().compare("https", Qt::CaseInsensitive) == 0) {
        addFinding(analysis.findings, "high", "HSTS eksik", "Strict-Transport-Security basligi eksik", "web", 20);
    }
    if (!hasHeader(input.rawHeaders, "x-frame-options")) {
        addFinding(analysis.findings, "medium", "X-Frame-Options eksik", "Clickjacking koruma basligi eksik", "web", 10);
    }
    if (!hasHeader(input.rawHeaders, "x-content-type-options")) {
        addFinding(analysis.findings, "medium", "X-Content-Type-Options eksik", "MIME sniffing koruma basligi eksik", "web", 8);
    }
    if (!hasHeader(input.rawHeaders, "referrer-policy")) {
        addFinding(analysis.findings, "low", "Referrer-Policy eksik", "Yonlendiren bilgi politikasi tanimli degil", "web", 4);
    }
    if (!hasHeader(input.rawHeaders, "permissions-policy")) {
        addFinding(analysis.findings, "low", "Permissions-Policy eksik", "Tarayici yetki politikasi tanimli degil", "web", 4);
    }

    if (hasHeader(input.rawHeaders, "cf-ray") || hasHeader(input.rawHeaders, "cf-cache-status")
        || serverHeader.contains("cloudflare", Qt::CaseInsensitive)
        || bodyText.contains("Attention Required!", Qt::CaseInsensitive)) {
        wafName = QStringLiteral("Cloudflare");
    } else if (hasHeader(input.rawHeaders, "x-sucuri-id") || hasHeader(input.rawHeaders, "x-sucuri-cache")
               || serverHeader.contains("Sucuri", Qt::CaseInsensitive)) {
        wafName = QStringLiteral("Sucuri");
    } else if (hasHeader(input.rawHeaders, "x-iinfo")
               || (hasHeader(input.rawHeaders, "x-cdn")
                   && headerValue(input.rawHeaders, "x-cdn").contains("incapsula", Qt::CaseInsensitive))
               || serverHeader.contains("Incapsula", Qt::CaseInsensitive)) {
        wafName = QStringLiteral("Imperva Incapsula");
    } else if (hasHeader(input.rawHeaders, "akamai-origin-hop") || hasHeader(input.rawHeaders, "x-akamai-transformed")) {
        wafName = QStringLiteral("Akamai");
    } else if (hasHeader(input.rawHeaders, "x-amz-cf-id")
               || (hasHeader(input.rawHeaders, "x-cache")
                   && headerValue(input.rawHeaders, "x-cache").contains("cloudfront", Qt::CaseInsensitive))
               || bodyText.contains("Generated by cloudfront", Qt::CaseInsensitive)) {
        wafName = QStringLiteral("AWS CloudFront/WAF");
    } else if (hasHeader(input.rawHeaders, "x-cdn")
               && headerValue(input.rawHeaders, "x-cdn").contains("fastly", Qt::CaseInsensitive)) {
        wafName = QStringLiteral("Fastly");
    }

    if (!wafName.isEmpty()) {
        addFinding(analysis.findings,
                   "info",
                   "WAF tespit edildi",
                   QString("Web katmaninda %1 koruma veya ters vekil izi goruldu").arg(wafName),
                   "web",
                   0);
    }

    if (!serverHeader.isEmpty()) {
        const QString version = extractVersion(serverHeader.toUtf8());
        if (!version.isEmpty()) {
            addFinding(analysis.findings,
                       "low",
                       "Sunucu surumu ifsa oluyor",
                       QString("Server basligi surum bilgisi donuyor: %1").arg(serverHeader),
                       "web",
                       5);
            analysis.cveCandidates.push_back({serverHeader.section('/', 0, 0), version});
        }
        if (serverHeader.contains("Apache/2.2", Qt::CaseInsensitive)
            || serverHeader.contains("nginx/1.14", Qt::CaseInsensitive)
            || serverHeader.contains("IIS/7", Qt::CaseInsensitive)) {
            addFinding(analysis.findings,
                       "medium",
                       "Eski web sunucusu izi",
                       QString("Server basligi eski surum isareti veriyor: %1").arg(serverHeader),
                       "web",
                       10);
        }
    }

    if (!poweredByHeader.isEmpty()) {
        const QString version = extractVersion(poweredByHeader.toUtf8());
        if (!version.isEmpty()) {
            addFinding(analysis.findings,
                       "low",
                       "Uygulama teknolojisi ifsa oluyor",
                       QString("X-Powered-By basligi surum bilgisi donuyor: %1").arg(poweredByHeader),
                       "web",
                       4);
            analysis.cveCandidates.push_back({poweredByHeader.section('/', 0, 0), version});
        }
    }

    for (const QNetworkCookie &cookie : input.cookies) {
        const QString cookieName = QString::fromUtf8(cookie.name());
        if (!cookie.isSecure() && input.url.scheme().compare("https", Qt::CaseInsensitive) == 0) {
            addFinding(analysis.findings,
                       "medium",
                       "Guvensiz cookie",
                       QString("'%1' cerezinde Secure bayragi yok").arg(cookieName),
                       "web",
                       8);
        }
        if (!cookie.isHttpOnly()) {
            addFinding(analysis.findings,
                       "low",
                       "HttpOnly eksik",
                       QString("'%1' cerezinde HttpOnly bayragi yok").arg(cookieName),
                       "web",
                       4);
        }
    }

    if (bodyText.contains("index of /", Qt::CaseInsensitive)) {
        addFinding(analysis.findings, "medium", "Dizin listeleme izi", "Yanitta dizin listeleme davranisi goruldu", "web", 12);
    }
    if (bodyText.contains("phpinfo()", Qt::CaseInsensitive) || bodyText.contains("server api", Qt::CaseInsensitive)) {
        addFinding(analysis.findings, "high", "Bilgi ifsasi", "Yanitta phpinfo veya ayrintili ortam bilgisi izi goruldu", "web", 18);
    }

    analysis.observation = QVariantMap{
        {"url", input.url.toString()},
        {"status", input.statusCode},
        {"server", serverHeader},
        {"version", extractVersion(input.bodyPreview)},
        {"waf", wafName}
    };
    return analysis;
}

ReconTlsAnalysis reconAnalyzeTlsState(const ReconTlsInput &input)
{
    ReconTlsAnalysis analysis;

    if (!input.hasCertificate) {
        addFinding(analysis.findings, "high", "TLS sertifikasi eksik", "HTTPS ucnoktasi istemciye sertifika sunmadi", "tls", 25);
        return analysis;
    }

    if (input.expiryDateUtc.isValid() && input.expiryDateUtc < QDateTime::currentDateTimeUtc()) {
        addFinding(analysis.findings, "high", "TLS sertifikasi suresi dolmus", "HTTPS sertifikasinin suresi dolmus", "tls", 25);
    } else if (input.expiryDateUtc.isValid() && QDateTime::currentDateTimeUtc().daysTo(input.expiryDateUtc) <= 21) {
        addFinding(analysis.findings, "medium", "TLS sertifikasi yakinda bitecek", "HTTPS sertifikasinin suresi yakinda dolacak", "tls", 8);
    }

    if (input.protocol < QSsl::TlsV1_2) {
        addFinding(analysis.findings, "medium", "Eski TLS protokolu", "Ucnokta TLS 1.2 alti protokol kullaniyor", "tls", 12);
    }

    for (const QString &cipherName : input.cipherNames) {
        if (cipherName.contains("RC4", Qt::CaseInsensitive) || cipherName.contains("3DES", Qt::CaseInsensitive)) {
            addFinding(analysis.findings,
                       "medium",
                       "Zayif TLS sifre paketi",
                       QString("TLS oturumu zayif cipher suite kullaniyor: %1").arg(cipherName),
                       "tls",
                       10);
            break;
        }
    }

    if (input.commonName.trimmed().isEmpty()) {
        addFinding(analysis.findings, "low", "Sertifika subject eksik", "Sertifikada belirgin common name bilgisi yok", "tls", 4);
    }

    if (input.issuerOrganization.contains("Let's Encrypt", Qt::CaseInsensitive)) {
        addFinding(analysis.findings, "info", "TLS gozlemi", "Sertifika saglayicisi Let's Encrypt olarak goruldu", "tls", 0);
    }

    analysis.observation = QVariantMap{
        {"protocol", static_cast<int>(input.protocol)},
        {"common_name", input.commonName},
        {"issuer", input.issuerOrganization},
        {"cipher", input.cipherNames.isEmpty() ? QString() : input.cipherNames.first()}
    };
    return analysis;
}
